### ISSUE TITLE
Basic API Usage

### ISSUE THREAD

**Issue by shakedmanes** [shakedmanes/mz-reports#2]
## Todo

- [ ] Create basic API for reports (CRUD)
- [ ] Adding tests for each API request
- [ ] Enable simple OAuth2 supporting Facebook and Google on each API request (Middleware)
