### ISSUE TITLE
Create basic DB structure

### ISSUE THREAD

**Issue by shakedmanes** [shakedmanes/mz-reports#3]
## Todo

- [ ] ***(OPTIONAL)*** Create basic structure of `User` collection, contains:
  - **User name** (User name of the user, usually for displaying purposes) 
  - **Email** (Email of the user, usually for identification purposes) 
- [ ] ***(MUST)*** Create basic structure of `Report` collection, contains:
  - **User id** (email or any id can be used for unique user, or even id of `User` collections)
  - **Body** (Body of the report, contains information regarding the report)
  - **Publish Time** (Time in milliseconds of publication)
  - **Location** (GEO Location coordinates or maybe id of `Location` collection described below)
- [ ] ***(MUST/OPTIONAL)*** Create basic structure of `Location` collection, contains:
  - **Location Coordinates** (GEO Location coordinates or Google maps coordinates)
  - **Location Display Name** (Name of the location in short, for displaying puposes)
  - **Location Address** (Address for the location for better searching techniques)
  - **Location Tags** (Tags or AKA names for the location for better searching techniques)
